# This is our DEVELOPMENT dockerfile.
#
# This uses Codelitt's Ruby 2.2 image found at:
# https://github.com/codelittinc/dockerfiles/blob/master/ruby/Dockerfile
FROM codelittinc/ruby:2.2
MAINTAINER Codelitt, Inc.

# Mount any shared volumes from host to container @ /share
VOLUME ["/share"]

# Install dependencies and rails-api
RUN apt-get update \
    && rm -rf /var/lib/apt/lists/* \
    && gem install --no-rdoc --no-ri \
    rails-api

WORKDIR /share

CMD ["/bin/bash", "-l"]
