# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db4c2561d92dd4ab2d21f3614fa57c533d6dad0e28efd8619483fff12df878f30a5e964ee5e31c6bf646ead5ee6e89fa4d77dd43c7c8c3ea705001654ed31b26

test:
  secret_key_base: 4ad25f5330e42afad372cc71c62bf81e05d94892a764e3d0602af2e9b8c209a2b440fb112757b25199bbb50a7affbf81f5fc0af8f8f8be98630ae4cd63718602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
